version: '3.0'

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: postgres
      POSTGRES_DB: encoder
    ports:
      - 5434:5432

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"

  # video_encode:
  #   build:
  #     context: ./video_encode
  #   container_name: video_encode
  #   volumes:
  #     - ./video_encode:/app
  #   depends_on:
  #     - postgres
  #     - rabbitmq
  #   networks:
  #     - application
  #     - observability

  video_admin:
    build:
      context: ./video_admin
    container_name: video_admin
    volumes:
      - ./video_admin:/app
    ports:
      - 3333:3333
    depends_on:
      - postgres
      - rabbitmq

  # video_catalog:
  #   build:
  #     context: ./video_catalog
  #   container_name: video_catalog
  #   volumes:
  #     - ./video_catalog:/app
  #   ports:
  #     - 3334:3333
  #   depends_on:
  #     - postgres
  #     - rabbitmq
  #   networks:
  #     - application
  #     - observability
  collector:
    image: otel/opentelemetry-collector-contrib:0.53.0
    #    image: otel/opentelemetry-collector-contrib:latest
    command: [ "--config=/conf/collector-config.yaml" ]
    volumes:
      - ./collector-config.yaml:/conf/collector-config.yaml
    ports:
      # - "9464:9464"
      - "4317:4317"
      - "4318:4318"
    depends_on:
      - zipkin-all-in-one

  # Zipkin
  zipkin-all-in-one:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"
  loki:
    image: grafana/loki:2.3.0
    volumes:
      - ./loki/loki-config.yml:/etc/loki/loki-config.yml
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/loki-config.yml

  promtail:
    image: grafana/promtail:2.3.0
    volumes:
      - ./promtail/promtail-config.yml:/etc/promtail/promtail-config.yml
      - ./video_admin/logs:/temp/logs/
    command: -config.file=/etc/promtail/promtail-config.yml

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
      - 9464:9464
