global:
  scrape_interval: 15s # Default is every 1 minute.

scrape_configs:
  - job_name: "collector"
    static_configs:
      - targets: ["collector:9464"]
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: postgres-exporter
    static_configs:
      - targets: ["postgres-exporter:9187"]
